version: '2'
services:
  tongue-twister-back:
    image: tongue-twister-api
    container_name : tongue-twister-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment: 
      - VIRTUAL_HOST=tonguetwisterapi.thanhlamtang.com
      - LETSENCRYPT_HOST=tonguetwisterapi.thanhlamtang.com
      - LETSENRYPT_EMAIL=thanh-lam@hotmail.fr
  mongo:
    container_name : mongo
    image : mongo
    volumes: 
      - /mongo:/data/db
    ports : 
      - "27017:27017"
